### ISSUE TITLE
structure for locales

### ISSUE THREAD

**Issue by sebastiankliem** [mammooc/mammooc.org#36]
instead of comments for structureing the locales we can use nested identifiers like this:

``` yml
en:
  dashboard:
    hi: Hi there!
```
